/**
 * 生产环境的无业务数据初始投影。
 *
 * 这里不能出现模拟员工、模拟卡槽或“已连接”之类的假状态；真实状态只能由
 * SQLite 缓存或原生能力事件覆盖。
 */
export const defaultSettings = Object.freeze({
  initialized: false,
  cabinetNumber: '',
  serialPort: '/dev/ttyS5',
  baudRate: '57600',
  serialPollEnabled: true,
  serialPollingEnabled: true,
  serialResponseTimeout: 700,
  serialResponseTimeoutMs: 700,
  serialPollInterval: 5000,
  serialPollingIntervalMs: 5000,
  slotStatusPushInterval: 60000,
  slotStatusReportIntervalMs: 60000,
  mqttStatusReportInterval: 300,
  pollingMode: 'GROUP',
  slotSortDirection: 'HORIZONTAL',
  singleGroupCount: 16,
  groupSize: 16,
  totalCount: 100,
  totalSlots: 100,
  deviceId: '',
  deviceCode: '',
  activationCode: '',
  communicationMode: 'MQTT',
  backendTransport: 'MQTT',
  httpHost: '',
  httpPort: 8082,
  httpServerAddress: '',
  mqttHost: '',
  mqttServerAddress: '',
  mqttPort: 1883,
  mqttHeartbeatInterval: 60000,
  mqttReconnectInitialInterval: 1000,
  mqttReconnectMaxInterval: 60000,
  faceRecognitionThreshold: 0.8,
  faceThreshold: 0.8,
  fingerThreshold: 0.8,
  fingerRecognitionThreshold: 0.8,
  fingerEnabled: '0',
  fingerprintEnabled: false,
  faceRecognitionTimeout: 30000,
  searchTimeout: 15000,
  searchIntervalTime: 3000,
  needFaceLiveness: false,
  captureTimeout: 8000,
  cameraFacing: 'front',
  cameraMirror: true,
  cameraRotation: 270,
  cameraFrameWidth: 640,
  cameraFrameHeight: 480,
  serialDataBits: 8,
  serialStopBits: 1,
  serialParity: 'NONE',
  serialCommandGapMs: 200,
  slotUiPushIntervalMs: 2000,
  cardNumberMode: 'VISIBLE',
  cardParseMode: '可视卡号',
  faceSyncIncludeFlags: 3,
  startupDataSyncEnabled: true,
  httpScheme: '',
  httpBasePath: '',
  mqttScheme: '',
  tcpServerAddress: '',
  tcpPort: 9009,
  systemBiometricEnabled: true,
  singleGroupPollingEnabled: false,
  ignoreTokenFetch: '',
  codeValueType: '',
  cardSuccessResponseType: '',
  toastDisplay: '',
  boardUpgradeIntervalMs: '',
  faceRegistrationResponseEnabled: '',
  tcpDoorCommandResponseEnabled: '',
  secondaryDoorEnabled: '',
  usbCardReaderEnabled: '',
  startCharacter: '',
  endCharacter: '',
  serialExtra: '',
  baudExtra: ''
})

export const defaultRuntime = Object.freeze({
  deviceAuthorization: Object.freeze({ state: 'PENDING', message: '授权状态待确认' }),
  recognitionEngine: Object.freeze({ state: 'PENDING', message: '等待原生人脸引擎状态' }),
  serial: Object.freeze({
    state: 'UNKNOWN',
    message: '等待原生串口状态',
    port: '',
    baudRate: 0,
    sentBytes: 0,
    receivedBytes: 0,
    pollingEnabled: false,
    totalSlots: 0,
    debugEventLimit: 300
  }),
  socket: Object.freeze({ state: 'DISCONNECTED', message: '后端通信未连接' }),
  http: Object.freeze({ state: 'PENDING', message: '等待HTTP注册/激活' })
})
