plugins {
    id 'com.android.library'
}

android {
    namespace 'com.xingyao.serialport'
    compileSdk 34
    ndkVersion "22.1.7171670"

    defaultConfig {
        minSdk 21
        targetSdk 33
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        ndk {
            abiFilters 'arm64-v8a', 'armeabi-v7a'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'consumer-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.22.1'
        }
    }

    // AAR 发布配置
    libraryVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "serialport-${variant.name}-${defaultConfig.versionName}.aar"
        }
    }
}

dependencies {
    implementation 'androidx.annotation:annotation:1.6.0'
    testImplementation 'junit:junit:4.13.2'
}
